/**:
  ros__parameters:
    world_name: "default"
    chassis_follow_pid:
      p: 5.0
      i: 0.0
      d: 1.0
      imin: -1.0
      imax: 1.0
      cmdmin: -1000.0
      cmdmax: 1000.0
    gimbal_pitch_pid:
      p: 11.0
      i: 0.0
      d: 1.0
      imin: -1.0
      imax: 1.0
      cmdmin: -1000.0
      cmdmax: 1000.0
    gimbal_yaw_pid:
      p: 11.0
      i: 0.0
      d: 0.0
      imin: -1.0
      imax: 1.0
      cmdmin: -1000.0
      cmdmax: 1000.0
